# nginx config on ipv4 proxy

events {
}

http {
  log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';

  # access_log /dev/stdout main;
  access_log off;
  error_log  /dev/stderr warn;

  http2                   on;
  http3                   on;
  quic_retry              on;
  add_header              Alt-Svc 'h3=":443"; ma=86400';

  merge_slashes off; # Required for ladder

  ssl_certificate           /etc/letsencrypt/live/heine7.de/fullchain.pem;
  ssl_certificate_key       /etc/letsencrypt/live/heine7.de/privkey.pem;
  #  ssl_trusted_certificate   /etc/letsencrypt/live/heine7.de/chain.pem;

  server {
    # server_name *.heine7.de;
    listen 80;
    listen [::]:80;

    location / {
      return 301 https://$host$request_uri;
    }

    # Let's Encrypt specific path to handle the certificate renewal
    location ^~ /.well-known/ {
      default_type "text/plain";
      allow        all;
      root         /var/letsencrypt/;
    }

    location /check-access {
      add_header Content-Type text/html;

      return 200 '<link rel="shortcut icon" href="https://heine7.de/favicon.png">\nYou have access <b>(http, proxy)</b>\n';
    }
  }

  server {
    server_name *.heine7.de;

    listen 443 ssl;
    # listen [::]:443 ssl ipv6only=on;
    listen [::]:443 ssl;

    location / {
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Host $server_name;
      proxy_set_header X-Forwarded-Port $server_port;
      proxy_set_header X-Forwarded-Scheme $scheme;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Forwarded-Ssl on;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header Accept-Encoding "";

      proxy_redirect off;

      client_body_buffer_size 512k;
      proxy_read_timeout 86400s;
      client_max_body_size 0;

      # proxy_pass_header Content-Type;

      # proxy_ssl_verify off;
      proxy_pass https://rocky.heine7.de:443/;

      # Websocket
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
    }

    location /check-access {
      add_header Content-Type text/html;

      return 200 '<link rel="shortcut icon" href="https://heine7.de/favicon.png">\nYou have access <b>(https, proxy)</b>\n';
    }
  }

  server {
    server_name kuma.heine7.de;

    # https://github.com/louislam/uptime-kuma/wiki/Reverse-Proxy
    listen 443 ssl;
    listen [::]:443 ssl;

    location / {
      proxy_set_header   X-Real-IP $remote_addr;
      proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header   Host $host;
      proxy_pass         http://uptime-kuma:3001/;
      proxy_http_version 1.1;
      proxy_set_header   Upgrade $http_upgrade;
      proxy_set_header   Connection "upgrade";
    }
  }
}
